server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: me.ssu.restapigradlerepectoring.global.config.jpa.MySQLDialect

logging:
  level:
    #    root: info
    #    me:
    #      ssu:
    #        myqadmin: debug
    #      amazonaws:
    #        internal:
    #          InstanceMetadataServiceResourceFetcher: error
    #        util:
    #          EC2MetadataUtils: error
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: off
        SQL: off
      springframework:
        data:
          redis: trace
          mongodb:
            core:
              MongoTemplate: debug
        boot:
          autoconfigure: error

#feign-client-config
feign:
  client:
    config:
      default:
        loggerLevel: FULL
#NONE : 로깅하지 않습니다. (DEFAULT)
#BASIC : Request Method와 URL 그리고 Reponse 상태 코드와 실행 시간을 로깅합니다.
#HEADERS : Request, Response Header 정보와 함께 BASIC 정보를 로깅합니다.
#FULL : Request와 Response의 Header, Body 그리고 메타데이터를 로깅합니다.

#external-api
external-api:

#springdoc-api-docs
springdoc:
  api-docs:
    enabled: true